Repository XiaoMi/rdsn, pull requests merged in 2018-06, with the labels that each got.

#86 json: bug fix of json decode & encode
  include/dsn/cpp/json_helper.h
  include/dsn/dist/replication/duplication_common.h
  src/core/core/perf_counters.cpp
  src/core/tests/json_helper_test.cpp
  src/core/tools/common/profiler_command.cpp
  src/dist/replication/meta_server/meta_backup_service.cpp
  src/dist/replication/meta_server/meta_data.h
  src/dist/replication/meta_server/server_state.cpp
  src/dist/replication/test/meta_test/unit_test/json_compacity.cpp
Labels: bug

#100 scripts: fix compile_thrift.py; remove useless file
  compile_thrift.py
  src/dsn.layer2_types.cpp
Labels: scripts

#103 scripts: add --compiler option for build; fix clang compile error
  include/dsn/tool-api/task.h
  run.sh
  scripts/linux/build.sh
  src/core/tests/autoref_ptr_test.cpp
  src/dist/block_service/local/local_service.cpp
  src/dist/block_service/local/local_service.h
  src/dist/replication/meta_server/meta_state_service_utils.h
Labels: enhancement, scripts

#104 *: force compiler to detect uninitialization
  bin/dsn.cmake
  src/dist/replication/lib/replica_backup.cpp
  src/dist/replication/lib/replication_app_base.cpp
  src/dist/replication/meta_server/distributed_lock_service_simple.cpp
  src/dist/replication/zookeeper/zookeeper_session.cpp
Labels: enhancement

#105 scripts: speed up compilation and travis using ccache
  .travis.yml
  bin/dsn.cmake
Labels: scripts

#107 scripts: fix clang warning due to ccache
  bin/compiler_info.cmake
  bin/dsn.cmake
Labels: scripts

#115 rdsn: fix asio_rpc_session bug which may cause double free
  include/dsn/c/api_utilities.h
  include/dsn/utility/autoref_ptr.h
  include/dsn/utility/endians.h
  src/core/tools/common/asio_net_provider.cpp
  src/core/tools/common/asio_rpc_session.cpp
  src/core/tools/common/thrift_message_parser.cpp
Labels: bug
