Repository XiaoMi/rdsn, pull requests merged in 2018-10, with the labels that each got.

#169 rpc: fix pegasus-186
  src/core/tools/common/asio_net_provider.cpp
Labels: type/bug-fix

#171 utility: move hpc_locks to utility
  include/dsn/utility/hpc_locks/autoresetevent.h
  include/dsn/utility/hpc_locks/autoreseteventcondvar.h
  include/dsn/utility/hpc_locks/benaphore.h
  include/dsn/utility/hpc_locks/bitfield.h
  include/dsn/utility/hpc_locks/readme.txt
  include/dsn/utility/hpc_locks/rwlock.h
  include/dsn/utility/hpc_locks/sema.h
  include/dsn/utility/synchronize.h
  src/core/tests/sema.cpp
Labels: type/refactoring

#170 scripts: disable tcmalloc to support valgrind memcheck
  bin/dsn.cmake
  run.sh
  scripts/linux/build.sh
  scripts/linux/format.sh
Labels: component/scripts, type/refactoring

#176 scripts: revert "shift" on some options in run.sh
  run.sh
Labels: component/scripts, type/bug-fix

#174 valgrind: use function-local initialization to implement singleton
  include/dsn/utility/singleton.h
  src/core/core/logging.cpp
  src/core/core/rpc_engine.cpp
  src/core/core/service_api_c.cpp
  src/core/core/service_engine.cpp
  src/core/core/task.cpp
  src/core/core/task_engine.cpp
  src/core/core/tool_api.cpp
  src/core/core/utils.cpp
  src/core/tests/netprovider.cpp
  src/core/tests/service_api_c.cpp
  src/core/tests/sim_lock.cpp
  src/core/tests/task_engine.cpp
  src/dist/replication/test/simple_kv/checker.cpp
  src/dist/replication/test/simple_kv/client.cpp
  src/dist/replication/test/simple_kv/common.cpp
  src/dist/replication/zookeeper/distributed_lock_service_zookeeper.cpp
  src/dist/replication/zookeeper/meta_state_service_zookeeper.cpp
Labels: type/memcheck

#173 valgrind: use static-allocated array to store mapping from task_code to task_spec
  include/dsn/cpp/json_helper.h
  include/dsn/tool-api/task_spec.h
  include/dsn/utility/singleton_vector_store.h
  src/core/core/task_spec.cpp
Labels: type/memcheck

#179 valgrind: fix leaks of messgae_utils
  include/dsn/cpp/message_utils.h
  include/dsn/tool-api/command_manager.h
  include/dsn/utility/enum_helper.h
  src/core/core/command_manager.cpp
  src/core/core/message_utils.cpp
  src/core/tests/message_utils_test.cpp
  src/core/tests/rpc.cpp
  src/core/tools/common/profiler_output.cpp
Labels: type/memcheck

#180 valgrind: fix leaks of aio_provider
  src/core/tools/common/native_aio_provider.linux.cpp
  src/core/tools/common/native_aio_provider.linux.h
  src/core/tools/common/native_aio_provider.win.cpp
  src/core/tools/common/native_aio_provider.win.h
  src/core/tools/common/providers.common.cpp
Labels: type/memcheck

#182 valgrind: fix leaks of rpc_engine
  src/core/core/rpc_engine.cpp
  src/core/core/rpc_engine.h
  src/core/tools/common/asio_net_provider.cpp
  src/core/tools/common/asio_net_provider.h
Labels: type/memcheck

#186 scripts: refactor compile_thrift.py
  compile_thrift.py
Labels: component/scripts

#183 valgrind: fix leaks of service_engine
  src/core/core/service_api_c.cpp
  src/core/core/service_engine.cpp
  src/core/core/service_engine.h
  src/core/core/tool_api.cpp
  src/core/tools/common/native_aio_provider.linux.cpp
Labels: type/memcheck

#187 restore_app: add table name validation
  src/dist/replication/ddl_lib/replication_ddl_client.cpp
Labels: type/bug-fix
