Repository XiaoMi/rdsn, pull requests merged in 2018-11, with the labels that each got.

#189 scripts: if 64-bit, find_library() should search the lib64
  bin/dsn.cmake
Labels: component/scripts

#188 replica: miscellaneous refactoring and fixes
  include/dsn/cpp/pipeline.h
  include/dsn/cpp/rpc_holder.h
  include/dsn/dist/fmt_logging.h
  include/dsn/dist/replication/replica_base.h
  include/dsn/dist/replication/replication.codes.h
  include/dsn/tool-api/task_queue.h
  src/core/core/task_engine.cpp
  src/core/core/task_queue.cpp
  src/core/tests/pipeline_test.cpp
  src/dist/replication/lib/prepare_list.cpp
  src/dist/replication/lib/prepare_list.h
  src/dist/replication/lib/replica.cpp
  src/dist/replication/lib/replica_learn.cpp
Labels: type/refactoring

#192 rpc: fix rpc_session::delay_recv to avoid unnecessary logging
  include/dsn/tool-api/network.h
  src/core/core/task_queue.cpp
Labels: type/enhancement

#194 server: support to disable write on table
  src/dist/replication/common/replication_common.cpp
  src/dist/replication/common/replication_common.h
  src/dist/replication/lib/replica.h
  src/dist/replication/lib/replica_2pc.cpp
  src/dist/replication/lib/replica_config.cpp
Labels: type/enhancement

#196 scripts: add compile flag -fno-omit-frame-pointer
  bin/dsn.cmake
Labels: component/scripts

#197 replica-server: add config-options and perf-counter for shared log th…
  src/dist/replication/common/replication_common.cpp
  src/dist/replication/common/replication_common.h
  src/dist/replication/ddl_lib/replication_ddl_client.cpp
  src/dist/replication/lib/mutation_log.cpp
  src/dist/replication/lib/mutation_log.h
  src/dist/replication/lib/replica_2pc.cpp
  src/dist/replication/lib/replica_stub.cpp
  src/dist/replication/lib/replica_stub.h
Labels: component/replica-server

#199 test/simple_kv: use code template from storage_engine/simple_kv
  compile_thrift.py
  src/dist/replication/storage_engine/simple_kv/simple_kv.app.example.h
  src/dist/replication/storage_engine/simple_kv/simple_kv.client.h
  src/dist/replication/storage_engine/simple_kv/simple_kv.server.h
  src/dist/replication/storage_engine/simple_kv/simple_kv.server.impl.cpp
  src/dist/replication/storage_engine/simple_kv/simple_kv.server.impl.h
  src/dist/replication/storage_engine/simple_kv/simple_kv_types.cpp
  src/dist/replication/test/simple_kv/CMakeLists.txt
  src/dist/replication/test/simple_kv/client.cpp
  src/dist/replication/test/simple_kv/client.h
  src/dist/replication/test/simple_kv/simple_kv.client.h
  src/dist/replication/test/simple_kv/simple_kv.code.definition.h
  src/dist/replication/test/simple_kv/simple_kv.server.h
  src/dist/replication/test/simple_kv/simple_kv.server.impl.h
  src/dist/replication/test/simple_kv/simple_kv.thrift
  src/dist/replication/test/simple_kv/simple_kv.thrift.annotations
  src/dist/replication/test/simple_kv/simple_kv.types.h
  src/dist/replication/test/simple_kv/simple_kv_types.cpp
  src/dist/replication/test/simple_kv/simple_kv_types.h
Labels: type/refactoring
