Repository XiaoMi/rdsn, pull requests merged in 2018-12, with the labels that each got.

#198 replica: remove functions useless in class replica
  src/dist/replication/lib/replica.cpp
  src/dist/replication/lib/replica.h
  src/dist/replication/lib/replica_check.cpp
Labels: type/refactoring

#202 shell: improve ls command to statistics total counts
  src/dist/replication/ddl_lib/replication_ddl_client.cpp
Labels: type/enhancement

#203 aio: use io_prep_pwritev to avoid memory copy
  include/dsn/tool-api/task.h
  src/core/core/disk_engine.cpp
  src/core/core/file_io.cpp
  src/core/core/task.cpp
  src/core/tools/common/native_aio_provider.linux.cpp
  src/core/tools/common/native_aio_provider.linux.h
  src/core/tools/common/native_aio_provider.posix.cpp
Labels: type/enhancement

#204 replica-server: support table level write throttling
  include/dsn/c/api_layer1.h
  include/dsn/dist/replication/replication.codes.h
  include/dsn/perf_counter/perf_counters.h
  src/core/core/partition_resolver_simple.cpp
  src/core/perf_counter/perf_counters.cpp
  src/dist/replication/common/replication_common.cpp
  src/dist/replication/common/replication_common.h
  src/dist/replication/lib/replica.cpp
  src/dist/replication/lib/replica.h
  src/dist/replication/lib/replica_2pc.cpp
  src/dist/replication/lib/replica_config.cpp
  src/dist/replication/lib/throttling_controller.cpp
  src/dist/replication/lib/throttling_controller.h
Labels: component/replica-server, type/enhancement

#212 meta: return forward address in configuration_query_by_index_response
  include/dsn/cpp/serialization_helper/dsn.layer2_types.h
  src/core/core/dsn.layer2_types.cpp
  src/dist/replication/meta_server/meta_service.cpp
  src/dist/replication/meta_server/meta_service.h
  src/dsn.layer2.thrift
Labels: component/meta-server, type/enhancement
