Repository XiaoMi/rdsn, pull requests merged in 2019-06, with the labels that each got.

#259 http: bugfix on http_message_parser
  src/core/tests/http_server_test.cpp
  src/core/tools/http/http_message_parser.cpp
  src/core/tools/http/http_message_parser.h
  src/core/tools/http/http_server.cpp
Labels: component/rpc, type/bug-fix

#260 doc: remove stale doc files and run.cmd
  doc/about.h
  doc/api.h
  doc/extensions.h
  doc/footer.rDSN.html
  doc/header.rDSN.html
  doc/how-to.h
  doc/install.h
  doc/rDSN.css
  doc/tools.h
  doc/tutorials.h
  run.cmd
Labels: component/docs

#261 perf-counter: add remote command to get perf-counters by substr/prefi…
  include/dsn/perf_counter/perf_counters.h
  src/core/perf_counter/perf_counters.cpp
Labels: component/perf-counter

#263 rpc: fix asio bug that causes coredump
  src/core/core/network.cpp
  src/core/tools/common/asio_rpc_session.cpp
  src/core/tools/common/asio_rpc_session.h
Labels: type/bug-fix
