Repository XiaoMi/rdsn, pull requests merged in 2019-01, with the labels that each got.

#213 fd: fix failure detection bug
  src/dist/failure_detector/failure_detector.cpp
Labels: type/bug-fix

#217 meta-server: re-implement returning forward address in configuration_query_b…
  include/dsn/cpp/serialization_helper/dsn.layer2_types.h
  src/core/core/dsn.layer2_types.cpp
  src/dist/replication/meta_server/meta_service.cpp
  src/dsn.layer2.thrift
Labels: type/bug-fix

#216 replica-server: remove checkpoint dirs when cold backup completed
  src/core/tests/service_api_c.cpp
  src/dist/replication/lib/mutation_log.cpp
  src/dist/replication/lib/mutation_log.h
  src/dist/replication/lib/replica.h
  src/dist/replication/lib/replica_backup.cpp
  src/dist/replication/replication.thrift
  src/dist/replication/test/simple_kv/case-402.act
Labels: type/enhancement

#219 scripts: use find_package to find system libs & optimize 3rdparty download logic
  bin/FindAIO.cmake
  bin/FindDL.cmake
  bin/FindRT.cmake
  bin/compiler_info.cmake
  bin/dsn.cmake
  thirdparty/download-thirdparty.sh
Labels: component/scripts

#214 add cluster balance indicator
  include/dsn/dist/replication/replication_types.h
  include/dsn/utility/math.h
  src/core/core/math.cpp
  src/dist/replication/common/replication_types.cpp
  src/dist/replication/meta_server/greedy_load_balancer.cpp
  src/dist/replication/meta_server/greedy_load_balancer.h
  src/dist/replication/meta_server/meta_service.cpp
  src/dist/replication/meta_server/server_load_balancer.h
  src/dist/replication/meta_server/server_state.cpp
  src/dist/replication/meta_server/server_state.h
  src/dist/replication/replication.thrift
  src/dist/replication/test/meta_test/balancer_simulator/balancer_simulator.cpp
  src/dist/replication/test/meta_test/unit_test/balancer_validator.cpp
  src/dist/replication/test/meta_test/unit_test/update_configuration_test.cpp
Labels: type/enhancement
