Repository XiaoMi/rdsn, pull requests merged in 2019-07, with the labels that each got.

#265 utils: fix a bug in table_printer and add several unit tests
  include/dsn/utility/output_utils.h
  src/core/core/output_utils.cpp
  src/core/tests/output_utils_test.cpp
Labels: type/bug-fix

#266 http: move http as a submodule of dist
  scripts/linux/build.sh
  src/core/CMakeLists.txt
  src/core/tools/CMakeLists.txt
  src/dist/CMakeLists.txt
  src/dist/http/CMakeLists.txt
  src/dist/http/http_message_parser.cpp
  src/dist/http/http_message_parser.h
  src/dist/http/http_parser.c
  src/dist/http/http_parser.h
  src/dist/http/http_server.cpp
  src/dist/http/pprof_http_service.cpp
  src/dist/http/pprof_http_service.h
  src/dist/http/root_http_service.h
  src/dist/http/test/CMakeLists.txt
  src/dist/http/test/http_server_test.cpp
  src/dist/http/test/run.sh
  src/dist/replication/lib/CMakeLists.txt
  src/dist/replication/meta_server/CMakeLists.txt
  src/dist/replication/test/meta_test/unit_test/CMakeLists.txt
  src/dist/replication/test/replica_test/unit_test/CMakeLists.txt
Labels: type/refactoring

#268 bugfix: fix error handling in filesystem::file_tree_walk
  include/dsn/utility/filesystem.h
  src/core/core/filesystem.cpp
  src/core/tests/CMakeLists.txt
  src/core/tests/clear.cmd
  src/core/tests/file_utils.cpp
  src/core/tests/nfs_test_file1
  src/core/tests/nfs_test_file2
Labels: type/bug-fix

#272 fd: fix ingeter overflow
  src/dist/failure_detector/failure_detector.cpp
Labels: type/bug-fix

#273 duplication: bugfix on pause_dup
  include/dsn/dist/replication/duplication_common.h
  src/dist/replication/meta_server/duplication/duplication_info.cpp
  src/dist/replication/meta_server/duplication/duplication_info.h
  src/dist/replication/meta_server/duplication/meta_duplication_service.cpp
  src/dist/replication/meta_server/duplication/meta_duplication_service.h
  src/dist/replication/test/meta_test/unit_test/duplication_info_test.cpp
  src/dist/replication/test/meta_test/unit_test/meta_duplication_service_test.cpp
Labels: component/duplication, type/bug-fix

#277 fd: improve failure detector to avoid getting now time out of lock
  src/dist/failure_detector/failure_detector.cpp
Labels: type/bug-fix

#276 configs: remove useless configs
  include/dsn/tool-api/global_config.h
  src/core/tests/aio.cpp
  src/core/tests/config-test-corrupt-message.ini
  src/core/tests/config-test-posix-aio.ini
  src/core/tests/config-test-sim.ini
  src/core/tests/config-test.ini
  src/core/tests/service_api_c.cpp
  src/dist/nfs/test/config.ini
  src/dist/nfs/test/nfs_test_file1
  src/dist/nfs/test/nfs_test_file2
  src/dist/replication/common/test/config-test.ini
  src/dist/replication/storage_engine/simple_kv/config.ini
  src/dist/replication/test/meta_test/unit_test/config-ddl-test.ini
  src/dist/replication/test/meta_test/unit_test/config-test.ini
  src/dist/replication/test/replica_test/unit_test/config-test.ini
  src/dist/replication/test/simple_kv/config.ini
  src/tests/dsn/config-test.ini
  src/tests/dsn/config-whitelist-test-failed.ini
  src/tests/dsn/config-whitelist-test.ini
Labels: component/config, type/refactoring

#278 utils: periodically memory release of tcmalloc
  include/dsn/dist/replication/replication.codes.h
  src/core/core/service_api_c.cpp
  src/dist/http/pprof_http_service.cpp
  src/dist/replication/common/replication_common.cpp
  src/dist/replication/common/replication_common.h
  src/dist/replication/lib/replica_stub.cpp
  src/dist/replication/lib/replica_stub.h
  src/tests/dsn/failure_detector.cpp
Labels: area/tcmalloc, type/enhancement

#282 minor refactoring on replica-server and meta-server
  include/dsn/dist/replication/replication_app_base.h
  src/dist/replication/lib/mutation_cache.cpp
  src/dist/replication/lib/mutation_cache.h
  src/dist/replication/lib/replica.cpp
  src/dist/replication/lib/replica.h
  src/dist/replication/lib/replica_chkpt.cpp
  src/dist/replication/lib/replica_config.cpp
  src/dist/replication/lib/replica_learn.cpp
  src/dist/replication/lib/replica_stub.cpp
  src/dist/replication/lib/replica_stub.h
  src/dist/replication/lib/replication_app_base.cpp
  src/dist/replication/meta_server/meta_state_service_utils_impl.h
  src/dist/replication/test/replica_test/unit_test/main.cpp
  src/dist/replication/test/replica_test/unit_test/run.sh
Labels: type/refactoring

#283 *: remove DSN_IN_CORE, improve BOOST linking, fix build.sh
  CMakeLists.txt
  bin/dsn.cmake
  scripts/linux/build.sh
  src/core/CMakeLists.txt
  src/core/tests/CMakeLists.txt
  src/dist/cli/shell/CMakeLists.txt
  src/dist/http/test/CMakeLists.txt
  src/dist/nfs/test/CMakeLists.txt
  src/dist/replication/common/test/CMakeLists.txt
  src/dist/replication/meta_server/CMakeLists.txt
  src/dist/replication/storage_engine/simple_kv/CMakeLists.txt
  src/dist/replication/test/meta_test/balancer_simulator/CMakeLists.txt
  src/dist/replication/test/meta_test/unit_test/CMakeLists.txt
  src/dist/replication/test/replica_test/unit_test/CMakeLists.txt
  src/dist/replication/test/simple_kv/CMakeLists.txt
  src/tests/dsn/CMakeLists.txt
  thirdparty/fix_s2_for_pegasus.patch
Labels: area/installation, component/scripts, type/refactoring

#281 dup: add duplication_sync_timer
  src/dist/replication/common/replication_common.cpp
  src/dist/replication/lib/CMakeLists.txt
  src/dist/replication/lib/duplication/duplication_sync_timer.cpp
  src/dist/replication/lib/duplication/duplication_sync_timer.h
  src/dist/replication/lib/duplication/replica_duplicator_manager.h
  src/dist/replication/lib/replica.cpp
  src/dist/replication/lib/replica.h
  src/dist/replication/lib/replica_stub.cpp
  src/dist/replication/lib/replica_stub.h
Labels: component/duplication, component/replica-server

#284 add prometheus to thirdparty
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
Labels: area/installation, component/scripts
