Repository XiaoMi/rdsn, pull requests merged in 2019-05, with the labels that each got.

#248 dup: add change_duplication_status on meta_server
  src/dist/replication/meta_server/duplication/duplication_info.cpp
  src/dist/replication/meta_server/duplication/duplication_info.h
  src/dist/replication/meta_server/duplication/meta_duplication_service.cpp
  src/dist/replication/meta_server/duplication/meta_duplication_service.h
  src/dist/replication/meta_server/meta_service.cpp
  src/dist/replication/test/meta_test/unit_test/duplication_info_test.cpp
  src/dist/replication/test/meta_test/unit_test/meta_duplication_service_test.cpp
Labels: component/duplication, component/meta-server

#251 rpc: minor refactoring on thrift_messsage_parser
  .gitignore
  src/core/tools/common/thrift_message_parser.cpp
  src/core/tools/common/thrift_message_parser.h
Labels: type/refactoring

#252 rpc: minor refactoring on message_reader
  include/dsn/cpp/rpc_stream.h
  include/dsn/tool-api/message_parser.h
  src/core/core/message_parser.cpp
  src/core/tests/message_reader_test.cpp
Labels: type/refactoring

#253 replication_app_base: add is_primary() function
  include/dsn/dist/replication/replication_app_base.h
  src/dist/replication/lib/replication_app_base.cpp
Labels: component/replica-server

#258 utility: fix simple_logger gc log file problem
  src/core/tools/common/simple_logger.cpp
Labels: component/utility

#257 use c++14 mode for compilation
  .travis.yml
  bin/dsn.cmake
  src/core/core/fail_point.cpp
  src/core/tests/CMakeLists.txt
Labels: type/build
