Repository XiaoMi/rdsn, pull requests merged in 2019-10, with the labels that each got.

#324 refactor: move replay related codes to mutation_log_replay
  src/dist/replication/lib/mutation_log.cpp
  src/dist/replication/lib/mutation_log_replay.cpp
Labels: type/refactoring

#321 feat(http): add http interface for get_app_envs
  src/dist/replication/meta_server/meta_http_service.cpp
  src/dist/replication/meta_server/meta_http_service.h
  src/dist/replication/test/meta_test/unit_test/meta_app_envs_test.cpp
  src/dist/replication/test/meta_test/unit_test/meta_http_service_test.cpp
  src/dist/replication/test/meta_test/unit_test/meta_test_base.h
Labels: component/http

#327 fix(backup): delay clearing obsoleted backup when it's still checkpointing
  src/dist/replication/lib/replica_backup.cpp
Labels: type/bug-fix

#326 refactor: remove useless functions from binary_reader
  include/dsn/utility/binary_reader.h
  src/core/core/binary_reader.cpp
Labels: type/refactoring

#323 refactor: move aio tests out from service_api_c
  src/core/tests/aio.cpp
  src/core/tests/service_api_c.cpp
Labels: type/refactoring

#332 fix: meta unnecessary assert
  src/dist/replication/meta_server/server_state.cpp
Labels: type/bug-fix
