Repository XiaoMi/rdsn, pull requests merged in 2021-06, with the labels that each got.

#834 feat(disk): add broken disk check while initialize
  include/dsn/utility/filesystem.h
  src/common/fs_manager.cpp
  src/common/fs_manager.h
  src/replica/replica_stub.cpp
  src/replica/replica_stub.h
  src/replica/test/replica_disk_test.cpp
  src/replica/test/replica_disk_test_base.h
  src/utils/filesystem.cpp
Labels: type/enhancement

#841 fix: add a destructor for `join_point`
  include/dsn/utility/join_point.h
Labels: type/bug-fix

#843 fix(graceful_exit): adjust the destructing order
  include/dsn/tool-api/timer_service.h
  src/aio/test/main.cpp
  src/meta/meta_service.cpp
  src/meta/meta_service.h
  src/meta/meta_service_app.cpp
  src/replica/replica_stub.cpp
  src/replica/replica_stub.h
  src/runtime/rpc/rpc_engine.h
  src/runtime/service_engine.cpp
  src/runtime/service_engine.h
  src/runtime/task/simple_task_queue.cpp
  src/runtime/task/simple_task_queue.h
  src/runtime/task/task_engine.cpp
  src/runtime/task/task_engine.h
  src/runtime/task/task_engine.sim.h
Labels: type/bug-fix

#838 fix: plog may be lost on going duplicating when replica re-open and then learn
  src/replica/replica_config.cpp
  src/replica/replica_learn.cpp
Labels: component/duplication, type/bug-fix
