Repository XiaoMi/rdsn, pull requests merged in 2021-08, with the labels that each got.

#866 feat: add function to get cluster migration info
  src/meta/greedy_load_balancer.cpp
  src/meta/greedy_load_balancer.h
  src/meta/meta_data.cpp
  src/meta/meta_data.h
  src/meta/test/greedy_load_balancer_test.cpp
Labels: component/load-balancer

#877 fix(split): adapt java client 2.0 version requests
  src/runtime/rpc/rpc_message.cpp
Labels: component/split

#873 feat: implement greedy_load_balancer::pick_up_move
  src/meta/greedy_load_balancer.cpp
  src/meta/greedy_load_balancer.h
  src/meta/test/greedy_load_balancer_test.cpp
Labels: component/load-balancer

#881 feat: implement greedy_load_balancer::pick_up_partition
  src/meta/greedy_load_balancer.cpp
  src/meta/greedy_load_balancer.h
  src/meta/test/greedy_load_balancer_test.cpp
Labels: component/load-balancer

#891 feat(split): add split reject counters
  src/replica/replica.cpp
  src/replica/replica.h
Labels: component/split, type/perf-counter

#890 refactor: move register_ctrl_commands from simple_load_balancer to partition_guardian
  src/meta/partition_guardian.cpp
  src/meta/partition_guardian.h
Labels: component/load-balancer

#895 feat(bulk_load): add replica-level bulk load reject write counter
  src/replica/replica.cpp
  src/replica/replica.h
  src/replica/replica_2pc.cpp
  src/replica/replica_stub.cpp
  src/replica/replica_stub.h
Labels: type/perf-counter, component/bulk-load

#892 refactor: move collect_replica from simple_load_balancer to meta_data
  src/meta/meta_data.cpp
  src/meta/meta_data.h
  src/meta/server_load_balancer.cpp
  src/meta/server_load_balancer.h
  src/meta/server_state.cpp
  src/meta/test/meta_data.cpp
  src/meta/test/meta_load_balance_test.cpp
  src/meta/test/update_configuration_test.cpp
Labels: component/load-balancer

#893 refactor: move construct_replica from simple_load_balancer to meta_data
  src/meta/meta_data.cpp
  src/meta/meta_data.h
  src/meta/server_load_balancer.cpp
  src/meta/server_load_balancer.h
  src/meta/server_state.cpp
  src/meta/test/meta_data.cpp
  src/meta/test/meta_load_balance_test.cpp
  src/meta/test/update_configuration_test.cpp
Labels: component/load-balancer

#896 refactor: move reconfig from simple_load_balancer to partition_guardian
  src/meta/partition_guardian.cpp
  src/meta/partition_guardian.h
Labels: component/load-balancer

#897 refactor: move get_ddd_partitions from server_load_balancer to partition_guardian
  src/meta/partition_guardian.cpp
  src/meta/partition_guardian.h
Labels: component/load-balancer
