Repository XiaoMi/rdsn, pull requests merged in 2021-09, with the labels that each got.

#899 refactor: remove simple_load_balancer
  src/meta/greedy_load_balancer.cpp
  src/meta/greedy_load_balancer.h
  src/meta/meta_data.h
  src/meta/meta_options.cpp
  src/meta/meta_options.h
  src/meta/meta_service.cpp
  src/meta/meta_service.h
  src/meta/meta_service_app.cpp
  src/meta/partition_guardian.h
  src/meta/server_load_balancer.cpp
  src/meta/server_load_balancer.h
  src/meta/server_state.cpp
  src/meta/server_state.h
  src/meta/test/balancer_validator.cpp
  src/meta/test/dummy_balancer.h
  src/meta/test/meta_partition_guardian_test.cpp
  src/meta/test/meta_test_base.cpp
  src/meta/test/update_configuration_test.cpp
  src/replica/storage/simple_kv/test/checker.cpp
Labels: type/config-change, component/load-balancer

#901 feat: support nfs server rate limit
  include/dsn/http/http_server.h
  src/nfs/nfs_client_impl.cpp
  src/nfs/nfs_server_impl.cpp
  src/nfs/nfs_server_impl.h
Labels: type/performance, type/config-change

#894 feat(perf_counter): add a perf_counter of server session
  include/dsn/tool-api/network.h
  src/runtime/rpc/network.cpp
Labels: type/perf-counter

#904 fix: fix bug that didn't copy primary
  src/meta/greedy_load_balancer.cpp
Labels: component/load-balancer

#908 refactor: add class ford_fulkerson
  src/meta/greedy_load_balancer.cpp
  src/meta/greedy_load_balancer.h
Labels: component/load-balancer

#909 feat: make secondary commit asynchronously
  src/replica/prepare_list.cpp
  src/replica/replica_2pc.cpp
  src/replica/storage/simple_kv/test/case-210.ini
  src/replica/storage/simple_kv/test/case-211.ini
  src/replica/storage/simple_kv/test/case-213.ini
Labels: type/enhancement, type/performance

#910 feat: support jemalloc
  bin/FindJemalloc.cmake
  bin/dsn.cmake
  run.sh
  scripts/linux/build.sh
  thirdparty/CMakeLists.txt
Labels: type/performance

#902 feat(task): add dynamic control of task queue length
  include/dsn/tool-api/task_queue.h
  src/runtime/task/task_engine.cpp
  src/runtime/task/task_engine.h
  src/runtime/task/task_queue.cpp
Labels: type/config-change, type/perf-counter, memory-control
