Repository XiaoMi/rdsn, pull requests merged in 2021-01, with the labels that each got.

#720 feat: add read limiter for hdfs
  src/block_service/hdfs/hdfs_service.cpp
  src/block_service/hdfs/hdfs_service.h
Labels: type/config-change

#715 fix: multiple asan errors
  include/dsn/utility/TokenBucket.h
  include/dsn/utils/time_utils.h
  src/aio/test/aio.cpp
  src/runtime/rpc/rpc_message.cpp
  src/utils/logging.cpp
  src/utils/simple_logger.cpp
  src/utils/test/priority_queue.cpp
  src/utils/time_utils.cpp
Labels: type/sanitize

#679 feat(split): add meta control split
  include/dsn/dist/replication/replication.codes.h
  include/dsn/dist/replication/replication_ddl_client.h
  include/dsn/dist/replication/replication_types.h
  src/client/replication_ddl_client.cpp
  src/common/replication_common.h
  src/common/replication_types.cpp
  src/meta/meta_service.cpp
  src/meta/meta_service.h
  src/meta/meta_split_service.cpp
  src/meta/meta_split_service.h
  src/meta/test/meta_split_service_test.cpp
  src/replication.thrift
Labels: component/split

#725 fix(split): message header should not be empty struct
  src/runtime/rpc/rpc_message.cpp
Labels: component/split

#681 feat(split): replica server handle pause and cancel status
  include/dsn/dist/replication/replication_types.h
  src/common/replication_types.cpp
  src/replica/replica_check.cpp
  src/replica/replica_context.cpp
  src/replica/replica_context.h
  src/replica/split/replica_split_manager.cpp
  src/replica/split/replica_split_manager.h
  src/replica/split/test/replica_split_test.cpp
  src/replication.thrift
Labels: component/split

#733 fix(asan): heap-use-after-free caused by replica_test_base::create_test_mutation
  src/replica/test/replica_test_base.h
Labels: type/sanitize

#735 fix(perf_counter): remove static map from counter_info
  src/runtime/profiler.cpp
  src/runtime/profiler_command.cpp
  src/runtime/profiler_header.h
Labels: type/sanitize

#738 fix(asan): heap-use-after-free in rpc_read_stream
  include/dsn/cpp/rpc_stream.h
  src/runtime/rpc/thrift_message_parser.cpp
Labels: type/sanitize

#728 feat: add throttling for read size and read qps
  include/dsn/dist/replication/replica_envs.h
  include/dsn/dist/replication/replication.codes.h
  src/common/replication_common.cpp
  src/meta/app_env_validator.cpp
  src/replica/replica.cpp
  src/replica/replica.h
  src/replica/replica_2pc.cpp
  src/replica/replica_throttle.cpp
  src/utils/throttling_controller.cpp
  src/utils/throttling_controller.h
Labels: type/perf-counter

#731 feat(split): add notify_stop_split rpc
  include/dsn/dist/replication/replication.codes.h
  include/dsn/dist/replication/replication_types.h
  src/common/replication_common.h
  src/common/replication_types.cpp
  src/meta/meta_service.cpp
  src/meta/meta_service.h
  src/meta/meta_split_service.cpp
  src/meta/meta_split_service.h
  src/meta/test/meta_split_service_test.cpp
  src/replica/split/replica_split_manager.cpp
  src/replication.thrift
Labels: component/split

#711 refactor: reimplement join point with less code
  include/dsn/utility/join_point.h
  src/utils/join_point.cpp
  src/utils/test/join_point.cpp
  src/utils/test/join_point_test.cpp
Labels: type/sanitize
